name: lint with ansible-lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install linter
        run: sudo apt update -y && sudo apt install -y ansible-lint

      - name: Lint tasks/main.yml
        run: ansible-lint -v tasks/main.yml
