name: lint with ansible-lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pyhton
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install linter
        run: pip install -r .github/workflows/requirements.txt

      - name: Lint tasks/main.yml
        run: ansible-lint -v tasks/main.yml
