name: lint with ansible-lint

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install linter
        run: pip install -r requirements.txt

      - name: Lint tasks/main.yml
        run: ansible-lint -v tasks/main.yml
